name: Actions
run-name: ${{ github.actor }}
on: [push]
jobs:
  homolog:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
      - name: Download dependecies
        run: |
          pip install -r requirements.txt --no-cache-dir
      - name: Testing API
        run: pytest .

  prod:
    runs-on: ubuntu-latest
    needs: homolog
    steps:
      - run: echo "Docker building"
      - run: docker compose up -d --build